game_project/game_communicator/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^gamecommunicator', views.gamecommunicator, name='gamecommunicator'),
]

game_project/game_project/urls.py
import os
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static
from game_project import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include("game_communicator.urls", namespace="communicator")),
    url(r'^', include("game_server.urls")),
    url(r'^', include("resthandler.urls")),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
]

if not "DYNO" in os.environ:
    #Let django serve static files if running locally
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

game_project/game_server/urls.py
"""Includes all game_server URLs"""

from django.conf.urls import url
from django.views.generic.base import TemplateView
from game_server import views

urlpatterns = [
    url(r'^register$', views.register, name='register'),
    url(r'^login$', views.login, name='login'),
    url(r'^resetpassword$', views.resetpassword, name='resetpassword'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^store$', views.store, name='store'),
    url(r'^boughtgames$', views.boughtgames, name='boughtgames'),
    url(r'^gamestorepage/(?P<gameid>\d+)$', views.gamestorepage, name='gamestorepage'),
    url(r'^playgame/(?P<gameid>\d+)$', views.playgame, name='playgame'),
    url(r'^buygame$', views.buygame, name='buygame'),
    url(r'^addgames$', views.addgames, name='addgames'),
    url(r'^accountdetails$', views.accountdetails, name='accountdetails'),
    url(r'^mygames$', views.mygames, name='mygames'),
    url(r'^deletegame/(?P<game_id>\d+)$', views.deletegame, name='deletegame'),
    url(r'^activategame/(?P<game_id>\d+)$', views.activategame, name='activategame'),
    url(r'^deactivategame/(?P<game_id>\d+)$', views.deactivategame, name='deactivategame'),
    url(r'^editgame/(?P<game_id>\d+)$', views.editgame, name='editgame'),
    url(r'^gamestats/(?P<game_id>\d+)$', views.gamestats, name='gamestats'),
    url(r'^user_verification/(?P<verification_bytes>[\w|\W]+)/$', views.verification_email,
        name='verification_email'),
    url(r'^reset_password/(?P<verification_bytes>[\w|\W]+)/$', views.reset_password,
        name='reset_password'),
    url(r'^social_registration', views.social_registration, name='social_registration'),
    url(r'^robots.txt$', TemplateView.as_view(template_name='game_server/robots.txt',
                                              content_type='text/plain')),
    url(r'^$', views.home, name='home'),
]

game_project/game_server/models.py
from django.db import models
from django.contrib.auth.models import User

class UserType(models.Model):
    '''
    Table Defines if an User is a Player or a Developer.
    '''
    user_id = models.OneToOneField(User, on_delete=models.CASCADE, related_name='type')
    developer = models.BooleanField()
    verification_bytes = models.CharField(max_length=64)

    def __str__(self):
        if self.developer:
            return self.user_id.username + " - " + "Developer"
        return self.user_id.username + " - " + "Player"

class GameList(models.Model):
    '''
    Table maps the developer with the games. All games added by developers are shows in this table
    This table includes the following details:
        > ID of user who uploaded the game
        > Name of game
        > Category of game
        > Description of game
        > Price of game set to maximum 7 digits with 2 decimal digits. Example is 64534.87
        > Image (screenshot) of the game for store page and store listing
        > URL for the game to load it to iframe
        > Number of times this game has been purchased
        > All time high score of game
        > Time added for release date
    '''
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    game_name = models.CharField(max_length=128, unique=True)
    category = models.CharField(max_length=64)
    description = models.TextField()
    price = models.DecimalField(max_digits=7, decimal_places=2)
    image = models.ImageField(upload_to='game_images/')
    url = models.CharField(max_length=512)
    num_of_purchases = models.PositiveIntegerField(default=0)
    high_score = models.IntegerField(blank=True, default=0, null=True)
    time_added = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.game_name

    def increment_purchases(self):
        """Used to increment the purchases, automatically called when a new PurchasedGame instance
           is created"""

        self.num_of_purchases += 1
        self.save()

    def update_score(self, score):
        """Increments the global high score. Should be called via the function with the same
           name in PurchasedGame"""

        if score > self.high_score:
            self.high_score = score
            self.save()


class PurchasedGames(models.Model):
    '''
    Table maps the Player with his purchased games.
    This table includes the following details:
        > ID of user who purchased the game
        > ID of the game purchased
        > High score of this user for this game
        > Purchase time for developer listing
    '''
    user_id = models.ForeignKey(User)
    game = models.ForeignKey(GameList)
    high_score = models.IntegerField(blank=True, default=0)
    game_state = models.TextField(blank=True, default="")
    purchase_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user_id.username + " - " + self.game.game_name

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        """If the model has no pk (yet) it has not been previously saved, which means it is a
           new purchase and game purchases must be incremented"""

        if not self.pk:
            self.game.increment_purchases()

        super(PurchasedGames, self).save(force_insert, force_update, using, update_fields)

    def update_score(self, score):
        """Used to update the stored score. Checks if higher than previous and also tries updating
           the global score"""

        if score > self.high_score:
            self.high_score = score
            self.game.update_score(score)
            self.save()

    def update_game_state(self, game_state):
        """Used for storing a game state in the game instance"""

        self.game_state = game_state
        self.save()

game_project/game_server/views.py
"""Includes all views that produce HTML output and other functionality crucial views"""

import random
from django.contrib import messages
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.core.mail import EmailMessage
from django.http import HttpResponseBadRequest, HttpResponseForbidden
from django.shortcuts import render, redirect, get_object_or_404
from django.utils.crypto import get_random_string
from game_server.form import UserForm, GameListForm, UserPasswordResetForm, UserEditForm
from game_server.models import GameList, PurchasedGames, UserType
from game_server.helperfunctions import user_owns_game, create_checksum, usertype_exists

#Unique key for payment. Seller ID == karhuserver
#Secret Key created by Payment Module == 272491baabdac31e5f7ca278941c9f95
SID = 'karhuserver'
SECRET_KEY = '272491baabdac31e5f7ca278941c9f95'

def home(request):
    """
    The main home page which displays the newest games added to the service
    """
    latest_games = GameList.objects.filter(active=True).order_by("-time_added")[:4]
    return render(request, "game_server/home.html", {'latest_games': latest_games})

def store(request):
    """
    Main store view which lists all games available in the store and provides search and sorting
    functionalities
    """

    ordering = ""
    game_list = None

    #Check first if any games have been added to the store yet
    if not GameList.objects.all().filter(active=True):
        store_empty = True
    else:
        store_empty = False

        if request.GET.get("search"):
            game_list = GameList.objects.filter(game_name__icontains=request.GET.get("search"),
                                                active=True)
        elif request.GET.get("order"):
            order = request.GET.get("order")
            if order == "title":
                ordering = "game_name"
            elif order == "genre":
                ordering = "category"
            elif order == "popularity":
                ordering = "-num_of_purchases"
            elif order == "release":
                ordering = "-time_added"
            elif order == "price":
                ordering = "price"
            if ordering:
                game_list = GameList.objects.order_by(ordering).filter(active=True)
            else:
                game_list = GameList.objects.all().filter(active=True)
        else:
            game_list = GameList.objects.all().filter(active=True)

    return render(request, "game_server/store.html",
                  {'games': game_list, 'store_empty': store_empty})

def gamestorepage(request, gameid):
    """
    The store page which displays product information for a specific product. This page also allows
    initing purchases if the user is a non-developer and doesn't own the game yet.
    """
    if request.user.is_authenticated and not usertype_exists(request.user):
        return redirect('social_registration')

    game = get_object_or_404(GameList, pk=gameid, active=True)

    #Recommend games based on the same genre/category, excluding the current game
    recommended_games = GameList.objects.filter(
        category=game.category, active=True).exclude(pk=gameid)

    if len(recommended_games) > 3:
        #This is does a random slice only since order_by('?') is very expensive
        start_index = int(random.random() * (len(recommended_games) - 3))
        recommended_games = recommended_games[start_index:start_index+3]

    if request.user.is_authenticated() and not request.user.type.developer:

        #Owned attribute is used by the template to determine if buy button should be shown
        owned = user_owns_game(request.user, gameid)

        # redirect user to home if user does not own the game and game is deactivated
        if not game.active and not owned:
            return redirect('home')

        #Payment Commands

        #Product ID concatenated with user id to prevent the same checksum (purchase link) from
        #being used by other users
        pid = '%s_%s' % (gameid, request.user.pk)
        checksum = create_checksum("pid={}&sid={}&amount={}&token={}",
                                   pid, SID, game.price, SECRET_KEY)
        return render(request, "game_server/gamestorepage.html",
                      {'game': game, 'author': GameList.objects.get(pk=gameid).user_id,
                       'owned': owned, 'pid': pid, 'sid': SID, 'checksum': checksum,
                       'recommended_games': recommended_games})
    return render(request, "game_server/gamestorepage.html",
                  {'game': game, 'author': GameList.objects.get(pk=gameid).user_id,
                   'recommended_games': recommended_games})

@login_required
@user_passes_test(usertype_exists, login_url='/social_registration', redirect_field_name=None)
def mygames(request):
    """
    Developer view
    Shows all games uploaded by the current user
    """
    if request.user.type.developer:
        return render(request, "game_server/mygames.html",
                      {'games': GameList.objects.filter(user_id=request.user)})
    return HttpResponseForbidden()


@login_required
@user_passes_test(usertype_exists, login_url='/social_registration', redirect_field_name=None)
def boughtgames(request):
    """
    Player view
    Shows all games bought by the current user
    """
    if not request.user.type.developer:
        purchased_games = PurchasedGames.objects.select_related().filter(user_id=request.user)
        return render(request, "game_server/boughtgames.html",
                      {'purchased_games': purchased_games})
    return HttpResponseForbidden()


@login_required
@user_passes_test(usertype_exists, login_url='/social_registration', redirect_field_name=None)
def playgame(request, gameid):
    """
    Player view
    Used to play game with gameid if the title has been purchased
    """
    if user_owns_game(request.user, gameid):
        return render(request, "game_server/playgame.html",
                      {'game': GameList.objects.get(pk=gameid)})
    return HttpResponseForbidden()


@login_required
@user_passes_test(usertype_exists, login_url='/social_registration', redirect_field_name=None)
def buygame(request):
    """
    Player view
    Return view from payment service which verifies the payment info and adds the game if the
    information has not been tampered with
    """
    if request.user.type.developer:
        return HttpResponseForbidden()

    pid = request.GET.get('pid')
    ref = request.GET.get('ref')
    result = request.GET.get('result')
    checksum = request.GET.get('checksum')
    checksum_new = create_checksum("pid={}&ref={}&result={}&token={}", pid, ref, result, SECRET_KEY)

    pid_data = pid.split('_')

    gameid = int(pid_data[0])
    userid = int(pid_data[1])

    try:
        game = GameList.objects.get(pk=gameid)
    except ObjectDoesNotExist:
        return HttpResponseBadRequest()

    if user_owns_game(request.user, gameid):
        return redirect('home')

    if checksum == checksum_new and request.user.pk == userid:
        if result == 'success':
            PurchasedGames.objects.create(user_id=request.user, game=game)
            messages.success(request, '%s has now been added to your game list!' % (game.game_name))
            return redirect('boughtgames')
        elif result == 'cancel':
            messages.warning(request, 'Payment unsuccessful. You have canceled the payment.')
            return redirect('boughtgames')
    messages.error(request, 'An error occured while processing your purchase.')
    return redirect('home')

def register(request):
    """
    Displays the user registration form and creates a new user based on the data,
    sending a verification email
    """
    if not request.user.is_authenticated:
        form = UserForm()
        if request.method == 'POST':
            form = UserForm(request.POST)
            if form.is_valid():
                username = form.cleaned_data['username']
                password = form.cleaned_data['password']
                email = form.cleaned_data['email']
                first_name = form.cleaned_data['first_name']
                last_name = form.cleaned_data['last_name']
                user_type = form.cleaned_data['user_type']
                user = User.objects.create_user(username=username, password=password, email=email,
                                                first_name=first_name, last_name=last_name,
                                                is_active=False)
                verification_code = get_random_string(length=64)
                save_type = UserType(user_id=user, developer=user_type,
                                     verification_bytes=verification_code)
                user.save()
                save_type.save()

                email = EmailMessage('Karhu Game Server User Verification',
                                     ("Kindly click the link below to verify your email address:\n"
                                      "http://%s/user_verification/%s/" % (request.get_host(),
                                                                           verification_code)),
                                     to=[email])
                email.send()
                messages.info(request, 'User successfully created, verification email sent!')
                return redirect('login')
        return render(request, "game_server/register.html", {'form': form})
    else:
        return redirect('home')

def verification_email(request, verification_bytes):
    """
    View used to activate users following registration if matching verification bytes are found

game_project/game_server/templates/game_server/account.html
{% extends 'game_server/base.html' %}

{% block content %}
<div class="container">


    <div class="omb_login">
    	        <h3 class="omb_authTitle">Edit Account</h3>

		<div class="row omb_row-sm-offset-3 omb_loginOr">
			<div class="col-xs-12 col-sm-6">
				<hr class="omb_hrOr">
			</div>
		</div>

		<div class="row omb_row-sm-offset-3">
			<div class="col-xs-12 col-sm-6">
			    <form class="omb_loginForm" action="" autocomplete="off" method="POST">
                      {% csrf_token %}
					<div class="input-group">
						<span class="input-group-addon"><i class="fa fa-address-book"></i></span>
                        <input autofocus="" class="form-control" id="id_first_name" maxlength="64" name="first_name" placeholder="First name" type="text" {% if form1.first_name.value %} value="{{form1.first_name.value}}" {% endif %} required />
					</div>
					<span class="help-block">{{form1.errors.first_name}}</span>


                    <div class="input-group">
						<span class="input-group-addon"><i class="fa fa fa-address-book-o"></i></span>
                        <input autofocus="" class="form-control" id="id_last_name" maxlength="64" name="last_name" placeholder="Last Name" type="text" {% if form1.last_name.value %} value="{{form1.last_name.value}}" {% endif %} required />
					</div>
					<span class="help-block">{{form1.errors.last_name}}</span>

                    <span class="help-block">{{form1.non_field_errors.0}}</span>

					<button class="btn btn-lg btn-primary btn-block" type="submit" name='action' value="update">Save</button>
				</form>
		<div class="row omb_row-sm-offset-3 omb_loginOr">
			<div class="col-xs-12 col-sm-6">
				<hr class="omb_hrOr">
			</div>
		</div>
                <form class="omb_loginForm" action="" autocomplete="off" method="POST">
                      {% csrf_token %}

					<div class="input-group">
						<span class="input-group-addon"><i class="fa fa-lock"></i></span>
                      <input class="form-control" type="password" maxlength="32" minlength="6" name="old_password" placeholder="Old Password" required />
					</div>
                    <span class="help-block">{{form2.errors.password}}</span>


					<div class="input-group">
						<span class="input-group-addon"><i class="fa fa-lock"></i></span>
                      <input class="form-control" id="id_password" maxlength="32" minlength="6" name="password" type="password" placeholder="New Password"  required />
					</div>
                    <span class="help-block">{{form2.errors.password}}</span>


                    <div class="input-group">
						<span class="input-group-addon"><i class="fa fa-lock"></i></span>
                        <input class="form-control" id="id_password1" maxlength="32" minlength="6" name="password1" type="password" placeholder="Confirm Password" required />
					</div>
                    <span class="help-block">{{form2.errors.password1}}</span>


                    <span class="help-block">{{form2.non_field_errors.0}}</span>

					<button class="btn btn-lg btn-primary btn-block" type="submit" name='action' value="changepassword">Change Password</button>
				</form>
			</div>
    	</div>
		<div class="row omb_row-sm-offset-3">
			<div class="col-xs-12 col-sm-3">
				<label class="checkbox">

				</label>
			</div>
		</div>
	</div>


</div>
{% endblock %}

game_project/game_server/templates/game_server/addgames.html
{% extends 'game_server/base.html' %}

{% block content %}
<div class="container">

    <div class="omb_login">
    	        <h3 class="omb_authTitle">Add A New Game</h3>

		<div class="row omb_row-sm-offset-3 omb_loginOr">
			<div class="col-xs-12 col-sm-6">
				<hr class="omb_hrOr">
			</div>
		</div>

		<div class="row omb_row-sm-offset-3">
			<div class="col-xs-12 col-sm-6">
			    <form class="omb_loginForm" action="" autocomplete="off" method="POST" enctype="multipart/form-data">
                      {% csrf_token %}

					<div class="input-group">
						<span class="input-group-addon"><i class="fa fa-gamepad"></i></span>
                      <input class="form-control" id="id_game_name" maxlength="128" name="game_name" {% if form.game_name.value %} value="{{form.game_name.value}}" {% endif %} placeholder="Game Title" type="text" required />
					</div>
                    <span class="help-block">{{form.errors.game_name}}</span>


                  	<div class="input-group">
						<span class="input-group-addon"><i class="fa fa-gears"></i></span>
                      <select class="form-control" id="id_category" name="category" required>
                          <option value="Action" {% if form.category.value == "Action" %}selected{% endif %}>Action</option>
                          <option value="Arcade" {% if form.category.value == "Arcade" %}selected{% endif %}>Arcade</option>
                          <option value="Adventure" {% if form.category.value == "Adventure" %}selected{% endif %}>Adventure</option>
                          <option value="Multiplayer" {% if form.category.value == "Multiplayer" %}selected{% endif %}>Multiplayer</option>
                          <option value="Sports" {% if form.category.value == "Sports" %}selected{% endif %}>Sports</option>
                          <option value="Racing" {% if form.category.value == "Racing" %}selected{% endif %}>Racing</option>
                          <option value="Fight" {% if form.category.value == "Fight" %}selected{% endif %}>Fight</option>
                          <option value="Strategy" {% if form.category.value == "Strategy" %}selected{% endif %}>Strategy</option>
                          <option value="Minigame" {% if form.category.value == "Minigame" %}selected{% endif %}>Minigame</option>
                          <option value="Puzzle" {% if form.category.value == "Puzzle" %}selected{% endif %}>Puzzle</option>
                          <option value="Educational" {% if host.category.value == "Educational" %}selected{% endif %}>Educational</option>
                      </select>
					</div>
                    <span class="help-block">{{form.errors.category}}</span>


                  	<div class="input-group">
						<span class="input-group-addon"><i class="fa fa-pencil"></i></span>
                      <textarea class="form-control" cols="40" id="id_description" minlength="6" name="description" placeholder="Description of Game" rows="5" required>{% if form.description.value %}{{form.description.value}}{% endif %}</textarea>
					</div>
                    <span class="help-block">{{form.errors.description}}</span>


                  	<div class="input-group">
						<span class="input-group-addon"><i class="fa fa-credit-card"></i></span>
                      <input class="form-control" id="id_price" name="price" step="0.01" type="number" {% if form.price.value %} value="{{form.price.value}}" {% endif %} placeholder="Price" required />
					</div>
                    <span class="help-block">{{form.errors.price}}</span>


                    <div class="input-group">
						<span class="input-group-addon"><i class="fa fa-file-picture-o"></i></span>
                      <input class="form-control" id="id_image" name="image" type="file" required />
					</div>
                    <span class="help-block">{{form.errors.image}}</span>


                    <div class="input-group">
						<span class="input-group-addon"><i class="fa fa-globe"></i></span>
                      <input class="form-control" id="id_url" maxlength="512" minlength="6" name="url" {% if form.url.value %} value="{{form.url.value}}" {% endif %} placeholder="Link of Game" type="text" required />
					</div>
                    <span class="help-block">{{form.errors.url}}</span>


                    <span class="help-block">{{form.non_field_errors.0}}</span>

					<button class="btn btn-lg btn-primary btn-block" type="submit">Add Game</button>
				</form>
			</div>
    	</div>
		<div class="row omb_row-sm-offset-3">
			<div class="col-xs-12 col-sm-3">
				<label class="checkbox">

				</label>
			</div>
		</div>
	</div>
</div>
{% endblock %}

game_project/game_server/templates/game_server/editgame.html
{% extends 'game_server/base.html' %}

{% block content %}
<div class="container">

    <div class="omb_login">
    	        <h3 class="omb_authTitle">Edit Game Details</h3>

		<div class="row omb_row-sm-offset-3 omb_loginOr">
			<div class="col-xs-12 col-sm-6">
				<hr class="omb_hrOr">
			</div>
		</div>

		<div class="row omb_row-sm-offset-3">
			<div class="col-xs-12 col-sm-6">
			    <form class="omb_loginForm" action="" autocomplete="off" method="POST" enctype="multipart/form-data">
                      {% csrf_token %}

					<div class="input-group">
						<span class="input-group-addon"><i class="fa fa-gamepad"></i></span>
                      <input class="form-control" id="id_game_name" maxlength="128" name="game_name" {% if form.game_name.value %} value="{{form.game_name.value}}" {% endif %} placeholder="Game Title" type="text" required />
					</div>
                    <span class="help-block">{{form.errors.game_name}}</span>


                  	<div class="input-group">
						<span class="input-group-addon"><i class="fa fa-gears"></i></span>
                      <select class="form-control" id="id_category" name="category" required>
                          <option value="Action" {% if form.category.value == "Action" %}selected{% endif %}>Action</option>
                          <option value="Arcade" {% if form.category.value == "Arcade" %}selected{% endif %}>Arcade</option>
                          <option value="Adventure" {% if form.category.value == "Adventure" %}selected{% endif %}>Adventure</option>
                          <option value="Multiplayer" {% if form.category.value == "Multiplayer" %}selected{% endif %}>Multiplayer</option>
                          <option value="Sports" {% if form.category.value == "Sports" %}selected{% endif %}>Sports</option>
                          <option value="Racing" {% if form.category.value == "Racing" %}selected{% endif %}>Racing</option>
                          <option value="Fight" {% if form.category.value == "Fight" %}selected{% endif %}>Fight</option>
                          <option value="Strategy" {% if form.category.value == "Strategy" %}selected{% endif %}>Strategy</option>
                          <option value="Minigame" {% if form.category.value == "Minigame" %}selected{% endif %}>Minigame</option>
                          <option value="Puzzle" {% if form.category.value == "Puzzle" %}selected{% endif %}>Puzzle</option>
                          <option value="Educational" {% if host.category.value == "Educational" %}selected{% endif %}>Educational</option>
                      </select>
					</div>
                    <span class="help-block">{{form.errors.category}}</span>


                  	<div class="input-group">
						<span class="input-group-addon"><i class="fa fa-pencil"></i></span>
                      <textarea class="form-control" cols="40" id="id_description" minlength="6" name="description" placeholder="Description of Game" rows="5" required>{% if form.description.value %}{{form.description.value}}{% endif %}</textarea>
					</div>
                    <span class="help-block">{{form.errors.description}}</span>


                  	<div class="input-group">
						<span class="input-group-addon"><i class="fa fa-credit-card"></i></span>
                      <input class="form-control" id="id_price" name="price" step="0.01" type="number" {% if form.price.value %} value="{{form.price.value}}" {% endif %} placeholder="Price" required />
					</div>
                    <span class="help-block">{{form.errors.price}}</span>


                    <div class="input-group">
						<span class="input-group-addon"><i class="fa fa-file-picture-o"></i></span>
                      <input class="form-control" id="id_image" name="image" type="file" />
					</div>
					<span class="help-block">Image : <a href="{{ form.image.value.url }}">{{ form.image.value }}</a></span>
                    <span class="help-block">{{form.errors.image}}</span>


                    <div class="input-group">
						<span class="input-group-addon"><i class="fa fa-globe"></i></span>
                      <input class="form-control" id="id_url" maxlength="512" minlength="6" name="url" {% if form.url.value %} value="{{form.url.value}}" {% endif %} placeholder="Link of Game" type="text" required />
					</div>
                    <span class="help-block">{{form.errors.url}}</span>


                    <span class="help-block">{{form.non_field_errors.0}}</span>

					<button class="btn btn-lg btn-primary btn-block" type="submit">Modify</button>
				</form>
              <br>
              <a href="{% url 'mygames' %}"><button class="btn btn-lg btn-primary btn-block" type="submit">Back</button></a>
			</div>
    	</div>
		<div class="row omb_row-sm-offset-3">
			<div class="col-xs-12 col-sm-3">
				<label class="checkbox">

				</label>
			</div>
		</div>
	</div>
</div>
{% endblock %}

game_project/game_server/templates/game_server/logout.html
{% extends 'game_server/base.html' %}

{% block content %}
  <h2>Log out</h2>
  <p>Successfully logged out</p>
{% endblock %}

game_project/game_server/templates/game_server/playgame.html
{% extends 'game_server/base.html' %}

{% block content %}
<script>
window.addEventListener('message', function (evt) {
  if (evt.data.messageType === 'SETTING') {
    document.getElementById('gameFrame').height = evt.data.options.height;
    document.getElementById('gameFrame').width = evt.data.options.width;
  } else if (evt.data.messageType === 'SCORE') {
    $.ajax({
      method: 'POST',
      url: "{% url 'communicator:gamecommunicator' %}",
      data: {
        'csrfmiddlewaretoken': '{{ csrf_token }}',
        'msgtype': 'score',
        'gameid': '{{game.pk}}',
        'score': evt.data.score
      }
    });
  } else if (evt.data.messageType === 'SAVE') {
    $.ajax({
      method: 'POST',
      url: "{% url 'communicator:gamecommunicator' %}",
      data: {
        'csrfmiddlewaretoken': '{{ csrf_token }}',
        'msgtype': 'save',
        'gameid': '{{game.pk}}',
        'gamestate': JSON.stringify(evt.data.gameState)
      }
    });
  } else if (evt.data.messageType === 'LOAD_REQUEST') {
    $.ajax({
      method: 'GET',
      url: "{% url 'communicator:gamecommunicator' %}",
      data: {
        'msgtype': 'load',
        'gameid': '{{game.pk}}'
      },
      success: function (data) {
        var msg;
        if (data === '') {
          msg = {
            'messageType': 'ERROR',
            'info': 'No saved game state exists'
          };
        } else {
          msg = {
            'messageType': 'LOAD',
            'gameState': JSON.parse(data)
          };
        }
        document.getElementById('gameFrame').contentWindow.postMessage(msg, '*');
      }
    });
  }
});
</script>
  <h2>{{game.game_name}}</h2>
  <iframe id=gameFrame src="{{game.url}}"></iframe>
{% endblock %}